import { siteImages } from "./image-registry";
import type { CatalogItem } from "./types";

export const catalogItems: CatalogItem[] = [
  {
    slug: "steklo", title: "Изделия из стекла", shortTitle: "Стекло",
    description: "Изготовление изделий из закалённого, осветлённого, матового, рифлёного и гнутого стекла по индивидуальным размерам.",
    intro: "Мы реализуем самые сложные проекты из стекла и металла, как по готовым проектам, так и по индивидуальным разработкам.",
    image: siteImages.catalog["steklo"].cover.src, imageAlt: siteImages.catalog["steklo"].cover.alt,
    features: ["Закалённое стекло", "Триплекс", "Осветлённое стекло", "Матовое и рифлёное стекло", "Стекло с рисунком"], gallery: siteImages.catalog["steklo"].gallery,
    seo: { title: "Изделия из стекла на заказ в Санкт-Петербурге", description: "Проектирование, изготовление и монтаж изделий из стекла по индивидуальным размерам в Санкт-Петербурге." },
  },
  {
    slug: "zerkala", title: "Зеркала на заказ", shortTitle: "Зеркала",
    description: "Зеркала для ванных комнат, жилых и коммерческих интерьеров по индивидуальным размерам.",
    intro: "Изготавливаем зеркала под разные задачи: выполняем точный замер, обработку кромки, вырезы и профессиональный монтаж.",
    image: siteImages.catalog["zerkala"].cover.src, imageAlt: siteImages.catalog["zerkala"].cover.alt,
    features: ["По индивидуальным размерам", "Обработка кромки", "Вырезы под розетки", "Подсветка", "Доставка и монтаж"], gallery: siteImages.catalog["zerkala"].gallery,
    seo: { title: "Зеркала на заказ в СПб", description: "Изготовление зеркал по индивидуальным размерам с доставкой и монтажом в Санкт-Петербурге." },
  },
  {
    slug: "dushevye-ograzhdeniya", title: "Душевые ограждения", shortTitle: "Душевые ограждения",
    description: "Душевые ограждения из закалённого стекла любой конфигурации и сложности.",
    intro: "Изготавливаем самонесущие, угловые и цельностеклянные душевые ограждения, шторки на ванну, двери в нишу и конструкции с раздвижными дверьми.",
    image: siteImages.catalog["dushevye-ograzhdeniya"].cover.src, imageAlt: siteImages.catalog["dushevye-ograzhdeniya"].cover.alt,
    features: ["Стеклянные шторки на ванну", "Угловые душевые ограждения", "Цельностеклянные ограждения", "Пятиугольные уголки", "Раздвижные двери", "Двери в нишу"], gallery: siteImages.catalog["dushevye-ograzhdeniya"].gallery,
    seo: { title: "Душевые ограждения из стекла в СПб", description: "Изготовление душевых ограждений из стекла по индивидуальным размерам. Замер, доставка и монтаж." },
  },
  {
    slug: "ograzhdeniya-dlya-saun-i-hammamov", title: "Стеклянные ограждения в сауну и хаммам", shortTitle: "Сауны и хаммамы",
    description: "Ограждения и двери для саун и хаммамов из безопасного закалённого стекла.",
    intro: "Изготавливаем стеклянные ограждения для сауны любой сложности. Стеклянные двери в сауну и хаммам.",
    image: siteImages.catalog["ograzhdeniya-dlya-saun-i-hammamov"].cover.src, imageAlt: siteImages.catalog["ograzhdeniya-dlya-saun-i-hammamov"].cover.alt,
    features: ["Двери в сауну", "Двери в хаммам", "Цельностеклянные ограждения", "Термостойкая фурнитура", "Индивидуальный размер"], gallery: siteImages.catalog["ograzhdeniya-dlya-saun-i-hammamov"].gallery,
    seo: { title: "Стеклянные двери и ограждения для сауны и хаммама", description: "Изготовление и монтаж стеклянных дверей и ограждений для саун и хаммамов в Санкт-Петербурге." },
  },
  {
    slug: "terrasy-i-ulichnye-ograzhdeniya", title: "Террасы и уличные ограждения", shortTitle: "Террасы",
    description: "Безрамное остекление террас и безопасные уличные ограждения из стекла.",
    intro: "Стеклянные ограждения сохраняют обзор и поступление солнечного света. Для улицы применяется прочное закалённое стекло триплекс.",
    image: siteImages.catalog["terrasy-i-ulichnye-ograzhdeniya"].cover.src, imageAlt: siteImages.catalog["terrasy-i-ulichnye-ograzhdeniya"].cover.alt,
    features: ["Остекление террас", "Уличные ограждения", "Ограждения балконов", "Стекло триплекс", "Нержавеющая фурнитура"], gallery: siteImages.catalog["terrasy-i-ulichnye-ograzhdeniya"].gallery,
    seo: { title: "Стеклянные ограждения для террас в СПб", description: "Производство и монтаж стеклянных ограждений и безрамного остекления для террас." },
  },
  {
    slug: "ofisnye-peregorodki", title: "Офисные перегородки из стекла", shortTitle: "Офисные перегородки",
    description: "Цельностеклянные и профильные офисные перегородки для современного рабочего пространства.",
    intro: "Перегородки из стекла позволяют разделить помещение, сохранив естественное освещение и ощущение открытого пространства.",
    image: siteImages.catalog["ofisnye-peregorodki"].cover.src, imageAlt: siteImages.catalog["ofisnye-peregorodki"].cover.alt,
    features: ["Цельностеклянные перегородки", "Алюминиевый профиль", "Рифлёное стекло", "Smart-стекло", "Перегородки с подсветкой"], gallery: siteImages.catalog["ofisnye-peregorodki"].gallery,
    seo: { title: "Стеклянные офисные перегородки в СПб", description: "Изготовление цельностеклянных и профильных офисных перегородок с монтажом." },
  },
  {
    slug: "mezhkomnatnye-dveri", title: "Межкомнатные двери из стекла", shortTitle: "Стеклянные двери",
    description: "Распашные и раздвижные межкомнатные двери из закалённого стекла.",
    intro: "Стеклянные межкомнатные двери изготавливаются по индивидуальным размерам с подбором фурнитуры и способа открывания.",
    image: siteImages.catalog["mezhkomnatnye-dveri"].cover.src, imageAlt: siteImages.catalog["mezhkomnatnye-dveri"].cover.alt,
    features: ["Распашные двери", "Раздвижные двери", "Матовое стекло", "Рифлёное стекло", "Фурнитура любого цвета"], gallery: siteImages.catalog["mezhkomnatnye-dveri"].gallery,
    seo: { title: "Межкомнатные стеклянные двери на заказ", description: "Изготовление и монтаж межкомнатных дверей из стекла в Санкт-Петербурге." },
  },
  {
    slug: "balkonnye-ograzhdeniya", title: "Балконные ограждения из стекла", shortTitle: "Балконные ограждения",
    description: "Проектирование и монтаж стеклянных ограждений балконов для частных и коммерческих объектов.",
    intro: "Выполняем разработку проектов промышленного ограждения балконов, согласование, изготовление и монтаж.",
    image: siteImages.catalog["balkonnye-ograzhdeniya"].cover.src, imageAlt: siteImages.catalog["balkonnye-ograzhdeniya"].cover.alt,
    features: ["Инженерный проект", "Закалённый триплекс", "Стоечное крепление", "Скрытое крепление", "Монтаж на высоте"], gallery: siteImages.catalog["balkonnye-ograzhdeniya"].gallery,
    seo: { title: "Балконные ограждения из стекла в СПб", description: "Проектирование, производство и монтаж безопасных стеклянных ограждений балконов." },
  },
  {
    slug: "polki-lyuki-i-ograzhdeniya", title: "Полки, люки и технические ограждения", shortTitle: "Полки и люки",
    description: "Внутренние стеклянные полки, ревизионные люки и технические ограждения.",
    intro: "Изготавливаем нестандартные изделия из стекла в точности по выполненным замерам и техническому заданию.",
    image: siteImages.catalog["polki-lyuki-i-ograzhdeniya"].cover.src, imageAlt: siteImages.catalog["polki-lyuki-i-ograzhdeniya"].cover.alt,
    features: ["Стеклянные полки", "Ревизионные люки", "Технические дверцы", "УФ-склейка", "Обработка кромки"], gallery: siteImages.catalog["polki-lyuki-i-ograzhdeniya"].gallery,
    seo: { title: "Стеклянные полки и технические люки на заказ", description: "Изготовление полок, люков, дверец и технических конструкций из стекла." },
  },
  {
    slug: "gnutye-stekla", title: "Гнутые стёкла", shortTitle: "Гнутые стёкла",
    description: "Радиусное и моллированное стекло для душевых, ограждений и интерьерных конструкций.",
    intro: "Выполняем изделия из гнутых стёкол сложной геометрии по индивидуальным проектам.",
    image: siteImages.catalog["gnutye-stekla"].cover.src, imageAlt: siteImages.catalog["gnutye-stekla"].cover.alt,
    features: ["Радиусное стекло", "Моллированное стекло", "Закаливание", "Сложная геометрия", "Индивидуальные шаблоны"], gallery: siteImages.catalog["gnutye-stekla"].gallery,
    seo: { title: "Гнутое и моллированное стекло в СПб", description: "Изготовление радиусного и моллированного стекла по индивидуальным размерам." },
  },
  {
    slug: "lestnichnye-ograzhdeniya", title: "Лестничные ограждения из стекла", shortTitle: "Лестничные ограждения",
    description: "Стеклянные ограждения лестниц на стойках, точечных креплениях и в зажимном профиле.",
    intro: "Проектируем безопасные лестничные ограждения для частных домов, общественных и коммерческих помещений.",
    image: siteImages.catalog["lestnichnye-ograzhdeniya"].cover.src, imageAlt: siteImages.catalog["lestnichnye-ograzhdeniya"].cover.alt,
    features: ["На стойках", "Точечные крепления", "Зажимной профиль", "Поручни", "Закалённый триплекс"], gallery: siteImages.catalog["lestnichnye-ograzhdeniya"].gallery,
    seo: { title: "Лестничные ограждения из стекла в СПб", description: "Изготовление и монтаж стеклянных ограждений лестниц по индивидуальному проекту." },
  },
];
